# Generated by Django 2.2.5 on 2021-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210225_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
