# Generated by Django 2.2.5 on 2021-02-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210225_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='email_validated',
        ),
    ]
