# Generated by Django 2.2.5 on 2021-02-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210217_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.URLField(null=True),
        ),
    ]
