# Generated by Django 2.2.5 on 2021-02-18 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210217_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, height_field=200, upload_to=None, width_field=300),
            preserve_default=False,
        ),
    ]
