# Generated by Django 2.2.5 on 2021-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210218_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.FileField(blank=True, max_length=200, upload_to='header_image/%Y/%m/%d/'),
        ),
    ]
